### ISSUE TITLE
Allow date range to be set / better communicated

### ISSUE THREAD

**Issue by rustymonkey** [MarkMpn/AutotuneWeb#1]
Thanks for an amazing tool! One of the issues that I've faced is that the results often don't match a manual autotune. Part of the reason, I think, is that the date ranges of the data used don't necessarily match because:

a) autotuneweb's UI doesn't indicate the date range that is used, so it's not clear to the user how to generate matching data via a manual autotune. This can be fixed with some additional messaging on the input screens. e.g. 'Autotune web will analyze this along with your data from <dd/mm/yyyy> until <dd/mm/yyyy> (inclusive).'

b) autotuneweb doesn't allow the user to set a date range. Fixing this is preferable to the above approach because in some cases the user will want to choose to set a range to analyze for which the data is relatively 'clean' (e.g.  so as to exclude days when a child forgets to make carb entries OR to exclude days with intense exercise that would skew the analysis).

e.g. something like:
Choose date range: _dd/mm/yyyy_ to _dd/mm/yyyy_

(with default values preset to past 1/2 full weeks)

Thanks!

**Comment by MarkMpn** [comment]
I've just updated the site now with an option to specify the number of days that will be used. The results email displays the date range used.

**Comment by rustymonkey** [comment]
Looks good--thanks! 

btw, I'm still getting different results between web and manual autotune, so I'll have to investigate further...
