### ISSUE TITLE
Not able to start program

### ISSUE THREAD

**Issue by chrisc93** [MarkMpn/AutotuneWeb#10]
I am trying to start up the application on an Ubuntu box. I have created the SQL Server table and had to add the extra column for DaysDuration.

I thought it would work, but I am still getting this error:
<pre>
Unhandled Exception: System.Data.SqlClient.SqlException: Invalid column name 'TimeZone'.
</pre>

Is there another column that I need to add to the Job table?

**Comment by MarkMpn** [comment]
Updated table schema in https://github.com/MarkMpn/AutotuneWeb/commit/6fded41e1b1738d9d727a1fb7c576200c89add53
