### ISSUE TITLE
Can you support http NS website

### ISSUE THREAD

**Issue by jizhongwen** [MarkMpn/AutotuneWeb#12]
Thsi tool is really good. I am using http to access the nightscout website,  it is hard for me to use https,  can you help me support http? Thank you,

**Comment by MarkMpn** [comment]
As the system is accessing very personal data, I'd much prefer to only do it over https. What is your problem using https?

**Comment by jizhongwen** [comment]
My nightscout server is http, it is hard for me to use https. The CA is complicated. I think hackers will not care about personal sugar data, the http is faster than https.

**Comment by jizhongwen** [comment]
I really hope you can support http. Thank you!

**Comment by MarkMpn** [comment]
I've enabled this now.

**Comment by jizhongwen** [comment]
Thank you very much.
