### ISSUE TITLE
Check for URL correctness before running job? (eg https check)

### ISSUE THREAD

**Issue by danamlewis** [MarkMpn/AutotuneWeb#17]
Most common user error I've seen this week (up to more than a dozen) has been people getting an error because they're running with http in their URL instead of https. I'm wondering if we can add a check on the URL before it goes off to run a job, and if it fails with http, retry with https?

**Comment by MarkMpn** [comment]
Yes, I think we can do some automated checking of this, I'll take a look

**Comment by MarkMpn** [comment]
I believe this is now fixed with c61a840, but let me know if there are still patterns of common errors we could do better to prevent.
