### ISSUE TITLE
No Autotune mail after submitting info

### ISSUE THREAD

**Issue by cinsanne** [MarkMpn/AutotuneWeb#19]
This morning I have submitted my information but have not received a mail with my result. When I resubmit, it says that I am number 8 in the queue....
Never had this issue before , is there a way to solve this?

**Comment by Fuzz2316** [comment]
Same. I show as number 43 in queue for the past few hours...

**Comment by MarkMpn** [comment]
There's a problem a the moment with it not getting resources to run the jobs on, I'm working on it.

**Comment by MarkMpn** [comment]
Jobs are processing again now, hopefully you should receive your results email shortly.
