### ISSUE TITLE
HTTP support

### ISSUE THREAD

**Issue by edwardmjc** [MarkMpn/AutotuneWeb#23]
Hi, AutotuneWeb is amazing! I'm a Loop user and using the Nightscout on HTTP protocol. But AutotuneWeb project only support HTTPS protocol. Is it possible to support HTTP? Thanks!

**Comment by danibjor** [comment]
With [Let’s Enceypt](https://letsencrypt.org/) there’s no reason not to run secure websites. Especially medical information.

**Comment by edwardmjc** [comment]
Thanks for reply, but in china, websites with domain on https must be filed and approved. I'm currently visiting my Nightscout site by IP address.

**Comment by MarkMpn** [comment]
What error do you get when trying to use an http URL? This should be supported since 6783c0f

**Comment by edwardmjc** [comment]
> What error do you get when trying to use an http URL? This should be supported since [6783c0f](https://github.com/MarkMpn/AutotuneWeb/commit/6783c0f656b4e27001cf07ce243b8e05963e8e3b)

Thanks for your work, It's OK for me now. It was an issue of my mailbox. Please close this issue.
