### ISSUE TITLE
AutotuneWeb errors

### ISSUE THREAD

**Issue by DiaBeaTes** [MarkMpn/AutotuneWeb#26]
Hello,
I’ve used AutotuneWeb regularly in the past few weeks. Today it keeps returning errors. https://autotuneweb.azurewebsites.net/Home/RunJob
![E7349E8D-8FF0-4849-B807-6412DB4DCD3E](https://user-images.githubusercontent.com/24800795/76145793-a0d32b80-6052-11ea-8c0e-d71dcaa16a7b.png)

**Comment by MarkMpn** [comment]
The Azure Batch pool had hit an error resizing to run some earlier jobs, and the backlog had exceeded the allowed limit which was causing this error. I've migrated all the jobs to another pool and they are processing normally again now.
