### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by cryptor90** [MarkMpn/AutotuneWeb#27]
Hello,

I have been using autotuneweb successfully in the past (AAPS user). But recently and also today I only receive an error message:
An error occured while processing your request.

Could someone help me please? :)

**Comment by MarkMpn** [comment]
Can you send me your NS url please? You can send it to me via Facebook Messenger if you prefer

**Comment by cryptor90** [comment]
> Can you send me your NS url please? You can send it to me via Facebook Messenger if you prefer

Sure :) it's https://cryptor-cgm.herokuapp.com/

**Comment by MarkMpn** [comment]
This should be fixed now with the latest update, please try again.

**Comment by cryptor90** [comment]
> This should be fixed now with the latest update, please try again.

Thanks a lot, now I am in the queue!
