### ISSUE TITLE
Error recieved

### ISSUE THREAD

**Issue by hockeymom3** [MarkMpn/AutotuneWeb#29]
Hi Mark every time I try to run auto tune it sends be an email saying an error occurred?? 
https://hockeymom3.herokuapp.com/

**Comment by MarkMpn** [comment]
Unfortunately I think this is related to Autotune itself rather than AutotuneWeb, so you may need to share your log file on the autotune gitter channel for support there as it looks to me like some incompatibility between the data coming from Nightscout and what Autotune is expecting
