### ISSUE TITLE
[Feature request] Please add Lyumjev

### ISSUE THREAD

**Issue by ArthurusDent** [MarkMpn/AutotuneWeb#33]
Hello,

I've seen that you added Fiasp. It would be great if you could add Lyumjev, too! 

Here is the data that AndroidAPS uses:
"Lyumjev: Peak 45min (+/- 5min) and DIA 5h (5h-7h or 4h-6h)"

Source: https://github.com/nightscout/AndroidAPS/issues/269

Does this help? https://github.com/nightscout/AndroidAPS/commit/05125af9e75c03017b88b7a1d8d828ddea9c0755

Love the website, thanks for all the work!

**Comment by MarkMpn** [comment]
Currently OpenAPS/Autotune doesn't appear to support Lyumjev. The only insulin absorption curves available are bi-linear, rapd-acting and ultra-rapid: https://github.com/openaps/oref0/blob/acb0150021e7bf284b6741a9510076a13f690747/lib/iob/total.js#L27

If/when Autotune adds support for Ljumjev I should be able to add it to the website.

**Comment by acbrom** [comment]
Hi there, is this now possible?
