### ISSUE TITLE
Stuck report generation

### ISSUE THREAD

**Issue by ArthurusDent** [MarkMpn/AutotuneWeb#34]
A few days ago there was some error while starting a new report und it doesn't seem to resolve on its own. If you need the exact URL, please let me know.
![Screenshot 2021-12-02 at 16-02-13 Home Page - Autotune](https://user-images.githubusercontent.com/6848629/144447656-b728b64a-97e1-4eff-8d9b-5d24dc9c3aac.png)

**Comment by MarkMpn** [comment]
I can't see any jobs still running from that long ago. If you can provide the full Nightscout URL I'll be able to investigate further.

**Comment by MarkMpn** [comment]
Thanks, I've marked that job as failed now if you want to try a new one.
