### ISSUE TITLE
Web getting wrong profile

### ISSUE THREAD

**Issue by klalle** [MarkMpn/AutotuneWeb#36]
Using aaps 3.0 rc3 and trying to run autotune web but it constantly fetches the wrong profile! Instead of the current profile, it tries to run on a temporary profile (125%) that an automation has created a while ago even though aaps is back on normal profile. 
![Screenshot_20220129-164745](https://user-images.githubusercontent.com/4532449/151668530-a2401b8f-6bfc-433a-b042-68eddca495f7.png)
I tried to save current profile again in NS but that didn't make a difference... I usually don't touch the NS profiles since aaps is only run on locale profiles which it only uploads to NS for display purposes.
Is there a way of tricking autotune to select correct profile, or is this a "bug" in aaps?

**Comment by MarkMpn** [comment]
Please add a Profile Switch event in Nightscout and select the profile you want it to use.

**Comment by maja-lofgren** [comment]
Thanks, that worked - took a while to find the careportal -checkbox ;)

**Comment by klalle** [comment]
Thanks that worked! took a while to find the careportal-checkbox ;)
