### ISSUE TITLE
Results page does not reload

### ISSUE THREAD

**Issue by awktane** [MarkMpn/AutotuneWeb#37]
https://github.com/MarkMpn/AutotuneWeb/blob/f264d915b8bbcc3cafe48c29074402857e0c264c/AutotuneWeb/Views/Results/Index.cshtml#L52

Line should be something like:

`setTimeout(() => window.location.reload(), 10000);`

to avoid "Uncaught TypeError: Illegal invocation" in some modern browsers like Edge.

**Comment by MarkMpn** [comment]
Thanks, this fix is live now!

**Comment by awktane** [comment]
No problem. After experiencing the 10 seconds (and considering the time for a run is usually in the realm of minutes and not tens of seconds) perhaps it would be better to make it 20000 or maybe 30000? I'm not sure how much load, cost, etc that page will incur if run too often.
