### ISSUE TITLE
autotuneweb.azurewebsites.net not working anymore

### ISSUE THREAD

**Issue by edwin-hendriks** [MarkMpn/AutotuneWeb#38]
I tried site https://autotuneweb.azurewebsites.net/ yesterday again since bout a year. The autotune job keeps running but never finishes.

![autotune job keeps running](https://user-images.githubusercontent.com/13136750/165471616-9f2c96fd-70a6-4378-afc8-2683050850e8.png)
 
Hope you can help or provide an alternative (because I do not have one; e.g. I also tried running autotune on WSL Ubuntu but failed during installation).

**Comment by MarkMpn** [comment]
Thanks, it should be working through the backlog again now. Please let me know if it still doesn't complete over the next few hours.

**Comment by edwin-hendriks** [comment]
Thanks Mark. It has been resolved.


Edwin Hendriks

+31625014678 | ***@***.***
