### ISSUE TITLE
autotuneweb stuck in running

### ISSUE THREAD

**Issue by Samhagberth** [MarkMpn/AutotuneWeb#42]
Hello my autotune is stuck in running I hope you can help me out

Your job is already running. It started at 08:49 UTC, and has been running for 438 minutes.

Please be patient and you will get your results by email as soon as it is complete.

93bc42435d4dec9fb86a061deb9eb6e649e284b2-b1121879-55b0-47d4-bd7f-cd8b4d39d9b7

**Comment by MarkMpn** [comment]
I'm not sure what happened with this job - I've deleted it from the system now so it should allow you to start a new one again.
