### ISSUE TITLE
No data of the requested type was found

### ISSUE THREAD

**Issue by Iskra1116** [MarkMpn/AutotuneWeb#51]
When I enter my Nightscout URL I get the following message:
The requested name is valid, but no data of the requested type was found.
What could it be?

I would be very happy about an answer.

**Comment by MarkMpn** [comment]
This indicates an error with the domain name you have entered. Please double-check the URL, ensuring it doesn't have any additional whitespace or other characters around it. If you still get the same error, please share the URL you are entering and I'll take a look.

**Comment by Iskra1116** [comment]
The error is still there.
I sent you the URL on Facebook. I hope that's ok for you.
It would be great if you could take a look at it.

**Comment by MarkMpn** [comment]
It seems that URL is only accessible over IPv6. The service AutotuneWeb is running on only supports IPv4, so it cannot connect to this site. You will need to expose Nightscout on an IPv4 address to be able to use it with AutotuneWeb.

**Comment by Iskra1116** [comment]
Thank you for the information and for taking the time to do it. I'll try making it available on an IPv4 address.
