### ISSUE TITLE
Clarify data policy for site - retention of email & URL

### ISSUE THREAD

**Issue by danamlewis** [MarkMpn/AutotuneWeb#7]
Can you add a policy or information to the site about how emails and NS URL are used, and stored, if at all?

**Comment by MarkMpn** [comment]
Addressed in https://github.com/MarkMpn/AutotuneWeb/commit/7710fd3eabe44a02ace6f9e233abc52653e4d1ea

**Comment by danamlewis** [comment]
Fantastic - thanks!
